# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/bookworm64"

  config.vm.define "servidor" do |s|
    s.vm.hostname = "ftp.example.test"
    s.vm.network "private_network", ip: "192.168.56.10"

    s.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end
end

  config.vm.define "cliente" do |c|
    c.vm.hostname = "cliente"
    c.vm.network "private_network", ip: "192.168.56.11"
    c.vm.provision "shell", inline: "apt-get update && apt-get install -y ftp filezilla && apt-get install lftp -y"
    c.vm.provision "shell", inline: <<-SHELL
      echo "set ssl:verify-certificate no" > /home/vagrant/.lftprc
      chown vagrant:vagrant /home/vagrant/.lftprc
      chmod 0644 /home/vagrant/.lftprc
    SHELL
  end
end
