# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/bookworm64"

  config.vm.define "servidor" do |s|
    s.vm.hostname = "ftp.example.test"
    s.vm.network "private_network", ip: "192.168.56.10"
    s.vm.provision "file", source: "file/vsftpd.conf", destination: "/tmp/vsftpd.conf"
    s.vm.provision "shell", path: "setup-ftp.sh"
end

  config.vm.define "cliente" do |c|
    c.vm.hostname = "cliente"
    c.vm.network "private_network", ip: "192.168.56.11"
    c.vm.provision "shell", path: "setupCli-ftp.sh"
  end
end
